### ISSUE TITLE
Alpha Review

### ISSUE THREAD

**Issue by H0R5E** [SNL-WaterPower/fbWecCntrl#2]
As requested, here is my alpha review:

I don't have the control system toolbox, so I can only look at your README.

## README.md

> NOTE: this code is not supported and users should not expect responses to issues

I think this is too strong as your first line, as there is a good chance that people will think that you mean the code does not work and leave. Perhaps an explanation of why the code is here (on Github and not in a static repo) would be useful.

> fbWecCntrl is set of

That's a typo

> and represents a fork of

"is a fork"?

The installation instructions seem clear, but I can't test them.

**Comment by H0R5E** [comment]
@ryancoe, there is a spelling mistake in the title of this repo:

"Feedback controller design **fo** wave energy converters (WECs)"

**Comment by ryancoe** [comment]
thanks @H0R5E
