### ISSUE TITLE
Differing order of variables in OneDOF_coDesign.mlx

### ISSUE THREAD

**Issue by Jeffalo1** [SNL-WaterPower/fbWecCntrl#3]
The PTO_param_names vector has a different order of variables than the PTO_param_mask in the OneDOF_coDesign.mlx file.
![image](https://user-images.githubusercontent.com/68615707/138719375-2b16086d-b250-4e11-898a-4c22ee2bb7a8.png)

**Comment by ryancoe** [comment]
Thanks @Jeffalo1! Fixed w. 96e57cb
